server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8

#mybatis:
#  type-aliases-package: com.example.entity
#  configuration:
#    map-underscore-to-camel-case: true # 驼峰命名法
#  mapper-locations:
#    - classpath: mapper/*.xml
