server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    rest:
      default-page-size: 20 # 每页默认记录数，默认为 20
      page-param-name: page  # 分页查询的参数，  page  代表页数
      limit-param-name: size # 分页记录数参数名，默认为 size
      sort-param-name: sort  # 分页查询排序参数名
      base-path: /  # 表示给所有请求路径增加前缀
      return-body-on-create: true # 添加数据陈宫时，返回数据
      return-body-on-update: true # 更新数据成功是返回数据